baseURL = "https://docs.ginuerzh.xyz/"
title = "Document"
theme = "beautifulhugo"
hasCJKLanguage = true
# googleAnalytics = "UA-98791308-1"

[params]
  #subtitle = "Build a beautiful and simple website in minutes"
  logo = "img/avatar-icon.png"
  # favicon = "img/favicon.ico"
  # dateFormat = "January 2, 2006" # default date format
  #commit = false
  #rss = true
  #comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
